module Day7Data where
    day7Data = [
                ("muted coral", [(1, "bright magenta"),(1, "dim aqua")]),
                ("muted orange", [(2, "bright red")]),
                ("dim olive", [(2, "dull silver"),(4, "posh blue")]),
                ("dim white", [(4, "shiny indigo"),(4, "posh tan"),(3, "faded blue")]),
                ("dotted salmon", [(5, "bright black"),(3, "bright purple"),(5, "bright olive")]),
                ("faded purple", [(4, "pale beige"),(2, "striped violet"),(3, "muted olive"),(4, "vibrant chartreuse")]),
                ("dark maroon", [(1, "muted chartreuse"),(1, "muted violet"),(2, "bright lime")]),
                ("bright tomato", [(4, "dark chartreuse"),(2, "striped blue"),(2, "drab magenta"),(2, "faded gray")]),
                ("light orange", [(2, "bright tomato"),(5, "muted olive"),(1, "mirrored green"),(3, "drab bronze")]),
                ("posh cyan", [(5, "pale blue"),(5, "mirrored bronze"),(4, "dim magenta")]),
                ("pale lime", [(4, "light violet"),(4, "dotted black"),(3, "pale chartreuse")]),
                ("striped lavender", [(4, "shiny yellow"),(1, "mirrored green"),(1, "light blue")]),
                ("dull orange", [(1, "shiny white"),(3, "clear crimson"),(5, "posh tan")]),
                ("posh lavender", [(5, "vibrant orange"),(3, "dim aqua")]),
                ("light beige", [(5, "dim silver"),(2, "bright teal"),(3, "dotted tomato")]),
                ("drab lime", [(5, "faded lavender"),(3, "muted violet"),(1, "muted coral")]),
                ("faded lavender", [(5, "wavy blue"),(2, "plaid aqua")]),
                ("dull bronze", [(2, "dark lavender"),(1, "dotted silver")]),
                ("plaid lavender", [(1, "drab red"),(4, "wavy lime"),(2, "shiny olive")]),
                ("vibrant plum", [(4, "clear indigo"),(3, "light bronze"),(1, "striped coral")]),
                ("dull cyan", [(4, "striped cyan"),(5, "bright magenta"),(2, "pale brown")]),
                ("clear gold", [(4, "faded black"),(1, "shiny chartreuse"),(1, "mirrored green")]),
                ("dotted olive", [(5, "striped cyan"),(2, "dark chartreuse"),(1, "bright aqua"),(1, "pale blue")]),
                ("light cyan", [(1, "mirrored green")]),
                ("faded tan", [(2, "dim teal"),(4, "wavy green")]),
                ("dull olive", [(1, "striped teal"),(2, "drab green"),(2, "light red")]),
                ("plaid red", [(2, "muted cyan")]),
                ("faded coral", [(1, "striped maroon")]),
                ("light aqua", [(2, "muted plum"),(5, "mirrored bronze"),(4, "striped coral"),(1, "posh violet")]),
                ("bright aqua", [(2, "pale coral"),(4, "mirrored bronze"),(1, "light gold"),(2, "plaid lime")]),
                ("muted yellow", [(1, "wavy blue"),(5, "drab violet"),(3, "wavy black"),(2, "bright teal")]),
                ("vibrant yellow", [(4, "dull silver"),(4, "dark tan"),(2, "drab magenta")]),
                ("clear purple", [(1, "posh bronze"),(5, "vibrant black"),(3, "bright bronze")]),
                ("faded tomato", [(2, "shiny turquoise"),(5, "vibrant yellow")]),
                ("muted gold", [(1, "vibrant purple"),(5, "clear aqua"),(1, "mirrored white")]),
                ("drab magenta", []),
                ("posh brown", [(5, "muted plum"),(5, "mirrored aqua"),(3, "wavy chartreuse"),(1, "dull lavender")]),
                ("bright red", [(3, "drab violet"),(3, "clear blue")]),
                ("striped red", [(4, "vibrant orange"),(2, "vibrant turquoise")]),
                ("dotted green", [(1, "pale green"),(2, "posh teal"),(1, "muted blue"),(2, "clear tomato")]),
                ("pale fuchsia", [(3, "dim blue")]),
                ("light plum", [(4, "clear green"),(3, "clear crimson"),(1, "vibrant aqua"),(5, "faded gray")]),
                ("dim violet", [(3, "faded bronze"),(5, "dark turquoise")]),
                ("wavy indigo", [(2, "pale green"),(2, "clear tomato"),(2, "dotted black")]),
                ("dark salmon", [(4, "dotted silver")]),
                ("plaid bronze", [(2, "shiny magenta")]),
                ("mirrored aqua", [(1, "wavy green"),(1, "striped bronze"),(4, "light blue")]),
                ("mirrored gray", [(2, "clear beige")]),
                ("wavy olive", [(3, "dim brown"),(5, "clear green"),(4, "pale white")]),
                ("vibrant magenta", [(3, "striped cyan"),(3, "mirrored purple")]),
                ("dotted teal", [(4, "pale coral")]),
                ("posh orange", [(1, "wavy chartreuse"),(2, "mirrored orange"),(5, "dark white"),(1, "vibrant salmon")]),
                ("dotted brown", [(5, "drab silver"),(5, "bright tomato"),(3, "mirrored coral"),(2, "striped bronze")]),
                ("posh purple", [(5, "striped purple"),(1, "wavy beige"),(3, "clear beige")]),
                ("dark bronze", [(5, "posh white"),(5, "muted coral"),(4, "light blue")]),
                ("plaid violet", [(5, "dark fuchsia")]),
                ("drab gray", [(5, "plaid bronze"),(4, "dark salmon"),(5, "mirrored blue")]),
                ("muted tan", [(1, "striped olive"),(5, "vibrant magenta"),(5, "mirrored green")]),
                ("wavy magenta", [(2, "striped beige"),(4, "vibrant blue")]),
                ("dull violet", []),
                ("drab blue", [(1, "drab red"),(4, "dark gray")]),
                ("shiny crimson", [(1, "shiny magenta"),(5, "shiny silver"),(4, "striped salmon"),(5, "light magenta")]),
                ("muted teal", [(2, "shiny teal"),(5, "dim fuchsia"),(2, "dim red")]),
                ("dotted gold", [(2, "clear red"),(1, "wavy beige")]),
                ("dotted white", [(4, "plaid chartreuse")]),
                ("muted lavender", [(1, "striped silver")]),
                ("vibrant teal", [(1, "faded blue")]),
                ("striped tan", [(3, "muted salmon"),(4, "striped purple"),(3, "striped silver")]),
                ("light blue", [(2, "drab violet")]),
                ("dim salmon", [(1, "pale chartreuse")]),
                ("dark lavender", [(2, "dull brown"),(5, "pale teal"),(2, "muted lime"),(4, "pale beige")]),
                ("wavy beige", [(4, "posh tan"),(3, "muted brown"),(1, "pale magenta"),(5, "muted magenta")]),
                ("drab olive", [(1, "striped indigo"),(2, "dull beige"),(5, "bright magenta")]),
                ("pale cyan", [(2, "bright olive")]),
                ("dark blue", [(1, "posh indigo"),(2, "bright lime")]),
                ("dark chartreuse", [(3, "muted brown"),(3, "light violet"),(1, "mirrored green")]),
                ("dim bronze", [(1, "muted plum"),(5, "pale red")]),
                ("dotted fuchsia", [(3, "drab violet")]),
                ("posh fuchsia", [(1, "mirrored maroon")]),
                ("bright coral", [(2, "vibrant gray"),(2, "drab aqua")]),
                ("dark orange", [(2, "bright salmon"),(1, "plaid cyan"),(3, "plaid beige")]),
                ("dotted turquoise", [(4, "wavy green"),(1, "plaid lavender"),(1, "dotted olive"),(1, "dark silver")]),
                ("plaid salmon", [(3, "faded plum"),(4, "dark teal"),(2, "wavy green")]),
                ("clear cyan", [(3, "dull tan"),(2, "shiny olive"),(5, "shiny brown")]),
                ("posh tan", [(5, "dim lime"),(1, "shiny indigo"),(2, "dark chartreuse")]),
                ("muted violet", [(1, "wavy blue"),(1, "dark silver")]),
                ("dull indigo", [(3, "posh plum"),(5, "shiny coral"),(5, "dull crimson")]),
                ("mirrored violet", [(2, "posh plum"),(5, "dark indigo")]),
                ("pale tomato", [(1, "bright tomato"),(3, "striped salmon"),(1, "posh silver")]),
                ("shiny tomato", [(3, "shiny coral"),(5, "striped orange"),(1, "posh bronze"),(1, "wavy silver")]),
                ("dull silver", [(3, "light violet"),(2, "dim white"),(2, "dull beige"),(3, "pale maroon")]),
                ("dark gray", [(5, "drab green"),(5, "mirrored green"),(4, "faded gray"),(3, "drab white")]),
                ("wavy orange", [(1, "light maroon"),(3, "shiny beige"),(5, "drab silver")]),
                ("pale lavender", [(4, "shiny white"),(4, "bright indigo"),(5, "shiny teal"),(3, "clear crimson")]),
                ("pale chartreuse", [(3, "dark lavender")]),
                ("posh green", [(1, "plaid plum"),(3, "drab maroon")]),
                ("clear lavender", [(1, "vibrant purple"),(4, "pale orange")]),
                ("dim red", [(1, "posh coral"),(5, "pale yellow"),(5, "plaid aqua"),(3, "striped bronze")]),
                ("light violet", []),
                ("dull aqua", [(3, "posh bronze"),(2, "muted plum")]),
                ("faded beige", [(5, "vibrant orange"),(5, "clear magenta")]),
                ("vibrant black", [(5, "wavy orange")]),
                ("faded silver", [(1, "wavy olive")]),
                ("dark brown", [(3, "light indigo"),(1, "muted salmon")]),
                ("mirrored green", []),
                ("plaid tomato", [(1, "faded gray"),(3, "striped teal"),(2, "dotted beige"),(2, "dark coral")]),
                ("faded salmon", [(1, "vibrant purple"),(1, "dark cyan"),(3, "muted maroon")]),
                ("faded white", [(1, "mirrored tan"),(2, "pale fuchsia"),(3, "wavy gray"),(3, "plaid maroon")]),
                ("posh crimson", [(2, "dull tan"),(4, "striped silver"),(1, "clear fuchsia")]),
                ("striped silver", [(5, "dull tan"),(3, "striped blue"),(1, "dark silver"),(1, "clear green")]),
                ("dim green", [(1, "striped coral"),(3, "plaid gray"),(4, "clear green"),(3, "drab indigo")]),
                ("shiny gold", [(2, "dark chartreuse"),(2, "bright silver"),(1, "striped bronze"),(2, "pale maroon")]),
                ("wavy coral", [(1, "clear magenta")]),
                ("bright white", [(4, "dim teal"),(4, "plaid violet"),(5, "dotted chartreuse")]),
                ("dull lime", [(5, "vibrant salmon"),(1, "wavy fuchsia")]),
                ("dark red", [(2, "mirrored gray"),(5, "drab tomato"),(1, "faded purple")]),
                ("mirrored cyan", [(5, "bright cyan")]),
                ("dim blue", [(3, "dull beige"),(3, "shiny white"),(4, "posh purple")]),
                ("pale teal", [(3, "striped tomato"),(1, "plaid plum"),(5, "mirrored green"),(1, "striped blue")]),
                ("posh silver", [(1, "light violet"),(3, "dull blue")]),
                ("faded black", [(2, "bright tomato"),(1, "striped teal"),(1, "dim maroon")]),
                ("posh plum", [(5, "faded gray")]),
                ("striped beige", [(4, "dotted fuchsia"),(1, "pale teal"),(5, "shiny cyan"),(5, "striped indigo")]),
                ("striped indigo", [(4, "muted olive"),(1, "dotted silver"),(3, "clear fuchsia"),(3, "dull orange")]),
                ("dull black", [(4, "dark gold"),(4, "dark tan"),(2, "pale orange"),(2, "light gold")]),
                ("dark yellow", [(3, "posh teal")]),
                ("vibrant gold", [(3, "dull cyan"),(1, "mirrored maroon")]),
                ("dull gray", [(5, "plaid plum"),(4, "mirrored aqua")]),
                ("muted chartreuse", [(4, "dull blue"),(1, "dull tan"),(2, "light green"),(4, "mirrored green")]),
                ("dim maroon", [(1, "striped teal")]),
                ("bright orange", [(3, "muted maroon"),(5, "muted tomato"),(4, "striped maroon"),(1, "faded gray")]),
                ("faded orange", [(3, "posh lime"),(1, "clear purple"),(4, "dotted magenta")]),
                ("dotted red", [(4, "plaid tan"),(1, "dull tan"),(2, "posh beige"),(5, "bright turquoise")]),
                ("dotted orange", [(4, "bright black")]),
                ("wavy plum", [(3, "dull plum"),(3, "dotted cyan")]),
                ("clear turquoise", [(2, "striped blue"),(4, "wavy plum"),(2, "dark olive"),(2, "striped maroon")]),
                ("wavy chartreuse", [(3, "shiny yellow")]),
                ("muted turquoise", [(2, "plaid indigo")]),
                ("dotted bronze", [(2, "pale red"),(3, "dull lavender"),(4, "striped crimson")]),
                ("clear black", [(3, "striped plum"),(3, "plaid violet"),(3, "shiny chartreuse"),(4, "bright tomato")]),
                ("shiny brown", [(5, "posh lime"),(1, "posh bronze"),(4, "wavy brown")]),
                ("posh bronze", [(1, "mirrored gray"),(2, "bright plum"),(5, "dark gold")]),
                ("dark crimson", [(4, "wavy orange"),(4, "wavy green"),(1, "muted brown"),(2, "dotted purple")]),
                ("faded red", [(2, "plaid violet"),(5, "dull orange"),(1, "mirrored tomato"),(3, "dim aqua")]),
                ("drab purple", [(1, "posh violet"),(1, "dotted cyan"),(3, "muted magenta"),(2, "wavy black")]),
                ("dotted beige", [(4, "shiny green"),(5, "striped maroon")]),
                ("dim magenta", [(1, "dull violet"),(3, "striped tomato")]),
                ("striped white", [(4, "dim maroon")]),
                ("vibrant tan", [(1, "bright lime"),(3, "faded black"),(3, "bright olive")]),
                ("bright olive", [(5, "drab orange"),(2, "drab black"),(4, "muted salmon")]),
                ("dark white", [(2, "mirrored beige"),(1, "bright teal"),(2, "posh beige")]),
                ("pale gold", [(5, "dark orange")]),
                ("vibrant indigo", [(1, "muted purple")]),
                ("faded turquoise", [(5, "pale indigo")]),
                ("faded bronze", [(1, "clear magenta"),(4, "faded gold")]),
                ("shiny gray", [(3, "striped crimson"),(2, "dim brown"),(3, "drab red")]),
                ("mirrored magenta", [(3, "wavy maroon"),(2, "pale beige")]),
                ("muted lime", [(4, "clear beige"),(5, "vibrant chartreuse"),(1, "dark turquoise"),(5, "dim crimson")]),
                ("vibrant crimson", [(1, "dotted fuchsia"),(1, "pale tomato"),(4, "dark turquoise")]),
                ("vibrant cyan", [(4, "mirrored brown"),(3, "wavy green")]),
                ("pale orange", [(1, "pale gray"),(2, "wavy green"),(5, "plaid plum")]),
                ("vibrant maroon", [(3, "bright red")]),
                ("light bronze", [(1, "dull blue"),(2, "posh crimson"),(5, "drab magenta")]),
                ("dim beige", [(4, "shiny yellow"),(4, "muted lavender")]),
                ("pale black", [(5, "mirrored fuchsia"),(4, "striped salmon"),(2, "dark turquoise"),(4, "dotted orange")]),
                ("dark turquoise", [(2, "striped purple"),(5, "bright teal")]),
                ("drab crimson", [(1, "faded turquoise"),(4, "vibrant crimson")]),
                ("pale maroon", [(3, "dull violet")]),
                ("bright salmon", [(5, "pale lime"),(4, "bright cyan")]),
                ("dull beige", [(3, "striped tomato"),(3, "dotted black")]),
                ("clear fuchsia", [(4, "shiny white"),(1, "mirrored fuchsia"),(4, "drab violet"),(1, "pale magenta")]),
                ("wavy gold", [(1, "vibrant black"),(2, "dotted indigo"),(5, "faded silver"),(1, "muted cyan")]),
                ("plaid maroon", [(3, "bright silver"),(5, "mirrored coral")]),
                ("dim cyan", [(3, "muted white"),(2, "wavy maroon")]),
                ("wavy purple", [(4, "bright teal"),(4, "dull turquoise"),(2, "vibrant aqua")]),
                ("muted cyan", [(3, "muted olive"),(3, "dim brown"),(4, "striped indigo")]),
                ("striped olive", [(2, "clear blue"),(2, "plaid indigo"),(3, "faded blue"),(3, "bright tomato")]),
                ("plaid orange", [(2, "bright indigo"),(2, "vibrant blue"),(5, "light gray"),(3, "faded tomato")]),
                ("striped plum", [(5, "posh gold"),(5, "bright bronze"),(2, "clear gold"),(2, "dark lime")]),
                ("dim crimson", [(4, "posh tan")]),
                ("drab aqua", [(3, "mirrored lime"),(4, "pale salmon"),(2, "wavy coral"),(4, "light brown")]),
                ("bright silver", [(4, "muted salmon"),(2, "striped salmon"),(5, "shiny turquoise")]),
                ("shiny beige", [(2, "light plum"),(4, "dim maroon"),(3, "pale brown"),(1, "pale maroon")]),
                ("shiny tan", [(4, "posh chartreuse"),(3, "dim tan"),(2, "pale green"),(5, "light tomato")]),
                ("wavy silver", [(3, "drab magenta")]),
                ("light brown", [(5, "dim fuchsia"),(3, "drab brown"),(4, "posh bronze"),(4, "bright cyan")]),
                ("striped green", [(5, "bright bronze"),(1, "striped gray"),(4, "wavy fuchsia"),(2, "striped indigo")]),
                ("faded brown", [(3, "dim brown")]),
                ("clear maroon", [(2, "mirrored magenta"),(3, "light cyan")]),
                ("dim black", [(3, "dull turquoise")]),
                ("muted bronze", [(3, "bright green")]),
                ("drab green", [(4, "posh gold")]),
                ("muted magenta", [(5, "muted brown"),(2, "dark chartreuse"),(5, "pale magenta")]),
                ("light chartreuse", [(5, "dim lime"),(1, "faded blue"),(5, "striped salmon")]),
                ("dull teal", [(3, "shiny teal")]),
                ("faded blue", [(5, "shiny indigo"),(5, "drab magenta"),(1, "dim lime"),(5, "striped teal")]),
                ("pale red", [(1, "dull brown"),(1, "bright tomato")]),
                ("dim indigo", [(2, "vibrant white")]),
                ("light gold", [(5, "shiny gold")]),
                ("clear green", [(2, "muted brown"),(4, "mirrored orange")]),
                ("posh red", [(1, "striped salmon"),(4, "posh silver"),(1, "pale blue")]),
                ("dull coral", [(2, "pale bronze"),(3, "shiny lime"),(5, "muted chartreuse")]),
                ("dotted plum", [(4, "plaid fuchsia"),(1, "mirrored coral"),(4, "clear beige"),(4, "bright gray")]),
                ("shiny black", [(5, "dotted indigo")]),
                ("drab white", [(5, "wavy lime"),(1, "posh bronze"),(3, "striped crimson")]),
                ("light fuchsia", [(3, "striped maroon"),(3, "muted coral"),(3, "light green")]),
                ("dotted tan", [(1, "wavy aqua"),(3, "dull turquoise")]),
                ("dark tomato", [(4, "dull violet"),(4, "shiny gold"),(2, "clear fuchsia"),(5, "striped teal")]),
                ("posh yellow", [(1, "dotted brown"),(5, "mirrored aqua")]),
                ("dark silver", [(3, "striped blue"),(3, "faded gray")]),
                ("clear chartreuse", [(2, "faded green"),(4, "vibrant lavender"),(5, "faded lime"),(5, "plaid lavender")]),
                ("dotted gray", [(3, "drab orange")]),
                ("vibrant beige", [(2, "bright olive"),(2, "plaid gold"),(3, "drab lime")]),
                ("light lime", [(1, "bright teal"),(1, "shiny cyan")]),
                ("dark aqua", [(4, "striped silver"),(1, "vibrant bronze"),(2, "plaid orange")]),
                ("shiny plum", [(3, "bright tomato"),(2, "clear crimson"),(2, "dull violet"),(2, "posh bronze")]),
                ("posh gray", [(4, "pale maroon"),(4, "plaid gold"),(3, "bright red")]),
                ("dark olive", [(4, "pale aqua"),(4, "bright brown"),(2, "dotted gray")]),
                ("dim tan", [(5, "mirrored orange"),(5, "pale magenta"),(3, "striped teal")]),
                ("drab chartreuse", [(3, "posh olive")]),
                ("clear lime", [(1, "vibrant gold"),(1, "faded beige"),(2, "dark lime"),(1, "faded gold")]),
                ("pale plum", [(5, "dim lavender"),(3, "dim turquoise"),(5, "muted aqua"),(4, "bright maroon")]),
                ("mirrored lime", [(4, "dim brown"),(2, "muted tomato")]),
                ("wavy violet", [(3, "mirrored chartreuse"),(5, "wavy gold"),(1, "faded gray"),(2, "dim maroon")]),
                ("posh coral", [(5, "bright turquoise"),(2, "dark fuchsia"),(4, "light crimson")]),
                ("shiny olive", [(2, "shiny coral"),(2, "posh bronze")]),
                ("faded yellow", [(5, "striped black"),(1, "dotted black")]),
                ("dotted chartreuse", [(3, "shiny maroon"),(2, "pale magenta"),(5, "wavy beige"),(5, "dim silver")]),
                ("dotted lavender", [(5, "muted silver"),(2, "striped purple")]),
                ("posh olive", [(5, "dotted yellow"),(1, "light salmon")]),
                ("shiny magenta", [(1, "striped yellow"),(1, "dotted yellow"),(1, "bright teal"),(3, "striped tan")]),
                ("clear red", [(5, "shiny teal")]),
                ("posh black", [(1, "shiny lime"),(1, "shiny salmon")]),
                ("dotted yellow", [(3, "dull gold"),(3, "dotted fuchsia"),(1, "shiny teal"),(2, "bright black")]),
                ("drab salmon", [(5, "plaid white"),(4, "dull lavender"),(4, "striped red"),(1, "posh bronze")]),
                ("shiny white", [(4, "striped tomato"),(4, "posh tan")]),
                ("clear olive", [(2, "bright plum"),(1, "clear green")]),
                ("light tomato", [(5, "dark purple")]),
                ("wavy crimson", [(2, "plaid plum"),(1, "vibrant tomato"),(4, "mirrored plum")]),
                ("muted indigo", [(1, "posh coral"),(1, "posh lavender"),(1, "muted coral"),(4, "faded lime")]),
                ("mirrored coral", [(3, "vibrant chartreuse"),(5, "muted magenta"),(2, "shiny salmon")]),
                ("bright violet", [(2, "dotted aqua"),(3, "dark yellow"),(1, "clear purple")]),
                ("mirrored white", [(1, "wavy chartreuse"),(3, "clear aqua"),(3, "bright tan")]),
                ("mirrored orange", []),
                ("drab violet", [(1, "drab magenta"),(4, "striped purple")]),
                ("pale white", [(1, "muted maroon"),(1, "clear crimson"),(3, "dotted fuchsia"),(3, "clear bronze")]),
                ("dull green", [(3, "mirrored fuchsia"),(4, "mirrored purple"),(2, "dotted green")]),
                ("pale tan", [(2, "dark fuchsia"),(5, "shiny white"),(4, "bright red"),(5, "posh plum")]),
                ("dull tan", [(5, "clear blue"),(1, "shiny turquoise")]),
                ("shiny turquoise", [(5, "striped teal"),(5, "clear crimson"),(4, "dim lime"),(2, "faded gray")]),
                ("shiny lime", [(1, "plaid indigo"),(1, "dim lime"),(5, "dotted beige"),(2, "dotted indigo")]),
                ("bright fuchsia", [(4, "plaid chartreuse"),(1, "drab red")]),
                ("wavy lavender", [(1, "muted olive"),(3, "shiny tan"),(5, "posh tan"),(4, "bright green")]),
                ("shiny violet", [(2, "dull lime"),(1, "dotted crimson"),(5, "dark lime"),(4, "shiny salmon")]),
                ("dotted maroon", [(1, "vibrant crimson")]),
                ("mirrored bronze", [(5, "posh silver"),(3, "mirrored lime")]),
                ("light green", [(1, "pale indigo"),(4, "vibrant chartreuse"),(1, "dull beige"),(5, "pale aqua")]),
                ("clear indigo", [(5, "dull turquoise")]),
                ("faded indigo", [(3, "muted tomato"),(2, "dotted fuchsia"),(4, "striped silver")]),
                ("shiny green", [(3, "striped salmon"),(4, "posh gold")]),
                ("muted crimson", [(4, "dark indigo")]),
                ("posh gold", [(4, "mirrored fuchsia"),(3, "muted brown"),(5, "dim lime")]),
                ("pale brown", [(3, "striped teal"),(2, "bright magenta")]),
                ("dark indigo", [(1, "muted tomato")]),
                ("light turquoise", [(2, "vibrant turquoise"),(2, "bright silver")]),
                ("shiny salmon", [(4, "pale gray")]),
                ("faded fuchsia", [(4, "light chartreuse"),(4, "posh lime")]),
                ("mirrored teal", [(4, "dull orange"),(1, "muted turquoise"),(2, "vibrant aqua"),(3, "faded blue")]),
                ("muted tomato", [(4, "drab green"),(3, "pale coral"),(5, "bright green")]),
                ("bright plum", [(4, "drab magenta"),(5, "light violet")]),
                ("striped brown", [(3, "vibrant turquoise"),(2, "plaid crimson"),(2, "wavy gray")]),
                ("muted white", [(5, "posh white")]),
                ("muted beige", [(3, "shiny cyan"),(4, "dim brown"),(3, "clear blue")]),
                ("dim coral", [(4, "wavy fuchsia")]),
                ("light indigo", [(2, "faded bronze"),(3, "dim magenta")]),
                ("dark black", [(5, "faded fuchsia"),(5, "mirrored olive"),(3, "dotted fuchsia")]),
                ("vibrant green", [(5, "bright purple"),(5, "muted chartreuse")]),
                ("plaid fuchsia", [(5, "bright aqua"),(2, "shiny indigo")]),
                ("light red", [(1, "vibrant aqua")]),
                ("light gray", [(2, "bright maroon"),(3, "dim turquoise"),(2, "faded gold")]),
                ("faded gold", [(3, "dull tan"),(2, "dotted black")]),
                ("striped lime", [(5, "muted fuchsia"),(3, "bright tomato"),(3, "drab teal")]),
                ("dim purple", [(4, "drab lavender")]),
                ("plaid aqua", [(4, "shiny indigo"),(2, "pale teal"),(3, "clear crimson"),(2, "striped purple")]),
                ("wavy fuchsia", [(4, "shiny turquoise"),(3, "muted salmon")]),
                ("bright lavender", [(4, "light gold"),(1, "bright magenta")]),
                ("striped tomato", []),
                ("bright indigo", [(4, "striped yellow"),(2, "clear crimson")]),
                ("dull tomato", [(5, "mirrored orange"),(3, "vibrant yellow")]),
                ("striped violet", [(1, "clear beige"),(4, "drab violet")]),
                ("vibrant turquoise", [(4, "light violet"),(2, "plaid gold")]),
                ("dim aqua", [(1, "bright teal"),(1, "wavy silver")]),
                ("dim lavender", [(2, "dull aqua"),(1, "plaid maroon"),(1, "light gray"),(4, "wavy maroon")]),
                ("vibrant violet", [(3, "posh gold"),(3, "shiny plum"),(4, "muted coral"),(4, "posh indigo")]),
                ("shiny chartreuse", [(5, "light violet"),(5, "plaid aqua")]),
                ("dull brown", [(1, "dull violet"),(1, "striped salmon"),(1, "wavy tan")]),
                ("muted silver", [(4, "dark red"),(2, "muted violet")]),
                ("striped blue", []),
                ("plaid silver", [(5, "dotted red"),(2, "faded teal"),(2, "faded olive")]),
                ("faded lime", [(3, "vibrant chartreuse")]),
                ("vibrant silver", [(3, "pale violet"),(3, "dark purple")]),
                ("clear tomato", [(3, "clear salmon"),(2, "light blue"),(2, "striped yellow")]),
                ("pale indigo", [(3, "clear green")]),
                ("dim turquoise", [(3, "pale teal"),(4, "shiny white")]),
                ("bright tan", [(3, "dotted beige")]),
                ("light tan", [(3, "dark teal"),(4, "muted brown")]),
                ("plaid white", [(3, "clear white"),(1, "dotted gold"),(1, "striped beige"),(3, "mirrored lavender")]),
                ("faded aqua", [(1, "bright plum")]),
                ("pale crimson", [(2, "mirrored magenta"),(2, "bright tan"),(4, "clear maroon")]),
                ("mirrored tomato", [(5, "bright bronze")]),
                ("bright bronze", [(3, "light red")]),
                ("plaid green", [(5, "striped green"),(3, "vibrant orange")]),
                ("drab teal", [(4, "plaid orange"),(4, "dotted teal"),(1, "vibrant chartreuse")]),
                ("posh chartreuse", [(3, "shiny teal"),(5, "dark tan"),(1, "dull olive")]),
                ("dim lime", [(3, "pale magenta"),(5, "striped tomato"),(2, "drab magenta"),(4, "striped blue")]),
                ("vibrant fuchsia", [(5, "plaid tomato"),(2, "dark coral"),(5, "mirrored lime"),(3, "plaid violet")]),
                ("mirrored turquoise", [(5, "wavy gray"),(3, "faded lavender"),(5, "muted fuchsia"),(5, "clear red")]),
                ("plaid magenta", [(1, "clear bronze"),(3, "muted cyan"),(3, "clear fuchsia")]),
                ("muted blue", [(4, "dotted indigo"),(5, "dim magenta")]),
                ("dotted lime", [(5, "vibrant aqua"),(1, "clear olive"),(1, "clear green")]),
                ("dim teal", [(5, "mirrored teal"),(4, "dotted teal"),(1, "mirrored tomato"),(2, "dull violet")]),
                ("plaid blue", [(5, "posh yellow"),(2, "mirrored crimson"),(4, "drab lavender"),(5, "plaid fuchsia")]),
                ("drab turquoise", [(1, "dotted plum"),(4, "dim gold"),(3, "mirrored white"),(2, "posh coral")]),
                ("striped maroon", [(2, "dim coral"),(4, "light cyan")]),
                ("vibrant blue", [(2, "dotted beige"),(4, "shiny green"),(3, "posh bronze"),(3, "posh olive")]),
                ("posh teal", [(5, "wavy beige"),(1, "striped black"),(3, "dotted teal")]),
                ("light yellow", [(1, "wavy olive"),(4, "shiny green"),(2, "clear teal")]),
                ("dim silver", [(1, "dark lime"),(1, "bright red")]),
                ("drab gold", [(4, "mirrored purple"),(3, "wavy maroon")]),
                ("striped gray", [(3, "wavy silver")]),
                ("bright maroon", [(5, "dull olive"),(4, "shiny gold")]),
                ("dotted silver", [(4, "dim tan"),(3, "posh tan"),(1, "clear crimson")]),
                ("dark green", [(4, "dim teal"),(5, "dull tan"),(1, "pale blue"),(5, "clear aqua")]),
                ("clear crimson", [(1, "posh gold"),(1, "dull violet"),(4, "mirrored green")]),
                ("bright green", [(5, "clear bronze"),(2, "wavy beige")]),
                ("drab yellow", [(2, "dim lavender"),(4, "striped indigo"),(4, "wavy green")]),
                ("bright brown", [(5, "drab maroon"),(2, "wavy beige")]),
                ("dark purple", [(5, "dark green")]),
                ("striped magenta", [(2, "vibrant blue"),(3, "muted yellow"),(3, "muted violet")]),
                ("dim orange", [(4, "dim fuchsia")]),
                ("drab brown", [(3, "plaid lavender"),(3, "mirrored plum"),(1, "faded black")]),
                ("light magenta", [(2, "clear beige"),(3, "shiny plum"),(3, "drab violet")]),
                ("faded gray", [(5, "mirrored green"),(3, "dull violet")]),
                ("dull crimson", [(1, "light gray"),(2, "dull gray")]),
                ("dotted blue", [(2, "faded lavender"),(2, "mirrored fuchsia"),(2, "dark blue")]),
                ("bright black", [(4, "dark chartreuse"),(5, "dim turquoise"),(5, "clear green"),(2, "striped teal")]),
                ("dim plum", [(4, "posh silver"),(3, "clear red")]),
                ("plaid gray", [(2, "clear silver"),(1, "posh lime"),(3, "striped gray"),(3, "dotted maroon")]),
                ("muted plum", [(4, "plaid aqua"),(1, "wavy gray"),(2, "light crimson"),(1, "dull red")]),
                ("dark magenta", [(4, "drab white"),(5, "dark lavender"),(5, "dim teal"),(5, "bright tan")]),
                ("clear brown", [(2, "mirrored teal"),(1, "striped silver"),(3, "mirrored purple"),(3, "faded gray")]),
                ("muted brown", [(1, "striped teal"),(3, "pale magenta"),(3, "striped tomato")]),
                ("bright gray", [(1, "dark fuchsia")]),
                ("wavy teal", [(5, "faded gold"),(5, "bright plum")]),
                ("wavy bronze", [(4, "posh turquoise"),(5, "muted red"),(3, "plaid crimson")]),
                ("shiny lavender", [(4, "bright tan"),(5, "drab teal"),(1, "shiny tan")]),
                ("pale silver", [(2, "mirrored beige"),(2, "drab crimson"),(4, "clear coral"),(3, "plaid brown")]),
                ("drab silver", [(1, "dark fuchsia"),(3, "drab magenta"),(4, "pale violet"),(5, "dull tan")]),
                ("bright chartreuse", [(1, "bright green")]),
                ("light salmon", [(2, "dim brown"),(4, "dark gold"),(2, "dull silver"),(4, "bright bronze")]),
                ("clear silver", [(4, "shiny gray"),(3, "drab green"),(5, "dim aqua"),(2, "drab olive")]),
                ("wavy tomato", [(3, "wavy green")]),
                ("dotted magenta", [(4, "posh purple")]),
                ("striped fuchsia", [(4, "vibrant maroon"),(4, "wavy tomato"),(3, "clear coral"),(3, "striped indigo")]),
                ("wavy green", [(1, "plaid aqua")]),
                ("clear plum", [(2, "wavy silver"),(3, "posh red"),(2, "dark gray"),(4, "dull brown")]),
                ("striped aqua", [(5, "dull gold"),(5, "mirrored green")]),
                ("dull maroon", [(5, "posh crimson"),(1, "muted tomato"),(5, "shiny gold")]),
                ("muted green", [(5, "faded blue"),(2, "dark tan"),(1, "mirrored bronze"),(2, "dotted crimson")]),
                ("mirrored purple", [(3, "clear green"),(2, "bright plum"),(4, "muted olive")]),
                ("dull purple", [(3, "plaid tan"),(5, "bright turquoise")]),
                ("pale coral", [(1, "clear olive")]),
                ("wavy gray", [(4, "light gold"),(5, "clear beige"),(4, "dim lime")]),
                ("wavy cyan", [(2, "striped olive")]),
                ("drab orange", [(1, "mirrored purple"),(2, "muted cyan"),(4, "posh purple")]),
                ("wavy lime", [(2, "striped indigo"),(3, "plaid plum"),(3, "drab violet"),(5, "muted magenta")]),
                ("dull blue", [(3, "drab magenta"),(1, "shiny teal"),(5, "mirrored fuchsia"),(2, "posh plum")]),
                ("dark teal", [(4, "shiny gray")]),
                ("pale beige", [(4, "faded blue"),(2, "dull red"),(3, "wavy beige"),(2, "dull tan")]),
                ("pale purple", [(2, "pale maroon")]),
                ("clear magenta", [(3, "muted olive"),(3, "bright teal"),(4, "dull salmon"),(2, "mirrored coral")]),
                ("dark tan", [(2, "plaid plum"),(5, "bright purple"),(4, "mirrored aqua")]),
                ("pale turquoise", [(3, "striped silver"),(2, "bright gray")]),
                ("shiny indigo", [(5, "mirrored fuchsia")]),
                ("plaid plum", []),
                ("plaid yellow", [(5, "bright beige"),(2, "dull tan"),(3, "dim crimson"),(1, "vibrant tomato")]),
                ("pale gray", [(5, "mirrored green"),(3, "plaid aqua"),(5, "pale violet")]),
                ("dotted crimson", [(5, "striped lavender"),(3, "shiny orange")]),
                ("plaid teal", [(2, "bright aqua"),(1, "posh olive"),(4, "shiny white"),(3, "dotted beige")]),
                ("dim brown", [(5, "striped tomato"),(5, "wavy black"),(3, "pale magenta")]),
                ("vibrant gray", [(4, "dark cyan"),(5, "drab purple"),(2, "mirrored crimson"),(4, "dark turquoise")]),
                ("light olive", [(2, "mirrored teal")]),
                ("posh aqua", [(5, "muted cyan"),(1, "plaid aqua"),(4, "mirrored plum")]),
                ("wavy tan", [(5, "clear fuchsia"),(1, "bright silver"),(5, "clear green"),(2, "bright teal")]),
                ("shiny cyan", [(3, "clear green"),(2, "bright black"),(3, "muted magenta"),(4, "mirrored orange")]),
                ("mirrored fuchsia", []),
                ("plaid beige", [(4, "wavy indigo"),(2, "bright green"),(1, "light magenta"),(2, "plaid tomato")]),
                ("drab cyan", [(5, "posh yellow"),(5, "dull white")]),
                ("drab tan", [(5, "wavy teal")]),
                ("muted aqua", [(3, "dim blue"),(1, "dim tan"),(3, "dim white")]),
                ("posh tomato", [(1, "clear purple"),(4, "vibrant crimson")]),
                ("pale aqua", [(5, "wavy fuchsia"),(2, "striped bronze")]),
                ("pale magenta", []),
                ("pale violet", [(1, "pale maroon")]),
                ("shiny teal", [(4, "striped tomato"),(1, "bright plum"),(1, "dim crimson"),(1, "plaid aqua")]),
                ("vibrant aqua", [(4, "mirrored green"),(4, "dim crimson"),(4, "faded blue")]),
                ("faded violet", [(1, "dark green"),(4, "mirrored maroon"),(1, "dark lavender"),(4, "bright black")]),
                ("mirrored tan", [(3, "mirrored magenta")]),
                ("faded cyan", [(5, "dotted crimson"),(1, "vibrant yellow"),(3, "shiny bronze")]),
                ("posh violet", [(4, "dotted beige")]),
                ("striped salmon", [(3, "posh purple"),(4, "clear green")]),
                ("mirrored indigo", [(2, "posh plum")]),
                ("dim gold", [(2, "posh gold"),(5, "faded gray")]),
                ("striped bronze", [(4, "mirrored orange")]),
                ("light white", [(3, "shiny plum"),(5, "striped indigo")]),
                ("muted purple", [(2, "dull orange"),(4, "drab maroon"),(4, "striped lavender"),(4, "dim teal")]),
                ("clear violet", [(5, "plaid yellow"),(3, "dark lavender"),(2, "wavy salmon")]),
                ("dotted black", [(1, "pale brown"),(1, "drab magenta"),(5, "plaid plum"),(5, "clear crimson")]),
                ("wavy black", [(5, "dim lime"),(4, "drab magenta"),(5, "mirrored orange"),(3, "plaid plum")]),
                ("plaid purple", [(4, "dull maroon")]),
                ("dotted cyan", [(4, "pale indigo"),(1, "dark coral")]),
                ("bright magenta", [(3, "clear fuchsia"),(2, "plaid plum"),(1, "clear blue"),(1, "dim white")]),
                ("posh blue", [(4, "dark purple")]),
                ("vibrant tomato", [(5, "muted tomato"),(5, "striped indigo"),(3, "clear crimson")]),
                ("drab black", [(3, "dotted orange"),(1, "pale tomato"),(2, "bright maroon")]),
                ("clear salmon", [(3, "pale maroon")]),
                ("mirrored beige", [(5, "dark lavender"),(5, "light violet"),(3, "striped tomato")]),
                ("muted gray", [(4, "muted gold"),(4, "clear indigo"),(4, "light maroon")]),
                ("posh indigo", [(4, "faded aqua")]),
                ("wavy red", [(3, "dim crimson"),(3, "clear red"),(3, "wavy beige"),(1, "vibrant purple")]),
                ("striped purple", [(4, "mirrored orange"),(3, "drab magenta"),(1, "bright plum"),(3, "striped teal")]),
                ("dull magenta", [(2, "dim crimson"),(2, "wavy olive")]),
                ("wavy brown", [(3, "faded tomato"),(1, "muted olive"),(2, "light tomato"),(1, "shiny orange")]),
                ("clear coral", [(2, "shiny maroon")]),
                ("dotted indigo", [(1, "posh silver")]),
                ("pale green", [(1, "striped crimson"),(3, "dim coral"),(5, "mirrored aqua"),(4, "light cyan")]),
                ("vibrant chartreuse", [(1, "clear beige"),(4, "muted magenta"),(2, "mirrored orange"),(5, "pale teal")]),
                ("muted salmon", [(1, "muted brown"),(5, "dark chartreuse"),(3, "posh gold"),(2, "shiny indigo")]),
                ("mirrored gold", [(2, "dotted bronze"),(3, "muted bronze"),(4, "clear orange")]),
                ("light purple", [(2, "light blue"),(5, "muted black"),(4, "posh indigo")]),
                ("clear aqua", [(2, "muted chartreuse"),(2, "dotted black"),(4, "wavy black")]),
                ("faded crimson", [(5, "shiny salmon"),(2, "striped plum")]),
                ("bright cyan", [(2, "wavy olive"),(3, "muted turquoise")]),
                ("pale yellow", [(1, "pale beige"),(3, "striped cyan")]),
                ("striped crimson", [(5, "shiny indigo"),(4, "dim brown"),(5, "muted salmon"),(5, "mirrored green")]),
                ("mirrored brown", [(1, "pale tomato"),(1, "striped purple"),(5, "posh gold")]),
                ("bright lime", [(2, "muted red"),(1, "pale lavender"),(1, "posh white")]),
                ("posh turquoise", [(3, "pale white")]),
                ("drab red", [(3, "dark fuchsia")]),
                ("striped gold", [(1, "mirrored brown"),(5, "drab lavender"),(4, "dotted lavender")]),
                ("dull red", [(2, "dim crimson")]),
                ("striped cyan", [(3, "striped salmon"),(3, "wavy beige"),(2, "dim tan")]),
                ("vibrant lime", [(1, "pale lavender")]),
                ("dotted violet", [(4, "plaid gold"),(3, "clear green")]),
                ("pale olive", [(3, "light orange"),(4, "wavy silver"),(4, "shiny indigo")]),
                ("plaid olive", [(4, "dim purple"),(5, "wavy chartreuse"),(3, "posh plum"),(4, "light violet")]),
                ("dotted coral", [(1, "striped olive"),(1, "wavy gray"),(1, "vibrant chartreuse")]),
                ("drab lavender", [(1, "mirrored crimson")]),
                ("mirrored crimson", [(3, "dark gold")]),
                ("vibrant orange", [(1, "light blue"),(3, "mirrored brown"),(2, "mirrored plum"),(3, "pale lavender")]),
                ("dull chartreuse", [(3, "dotted bronze"),(3, "striped teal")]),
                ("wavy turquoise", [(4, "muted fuchsia")]),
                ("shiny purple", [(5, "drab salmon")]),
                ("plaid brown", [(2, "bright green"),(5, "clear aqua"),(2, "plaid plum")]),
                ("pale bronze", [(3, "bright red"),(3, "pale black"),(1, "wavy lime"),(4, "light maroon")]),
                ("vibrant white", [(5, "striped yellow"),(4, "dark tan")]),
                ("mirrored blue", [(1, "plaid indigo"),(5, "muted chartreuse"),(2, "plaid lime"),(2, "drab green")]),
                ("wavy aqua", [(4, "mirrored orange")]),
                ("drab bronze", [(1, "bright purple"),(5, "dim coral"),(4, "shiny green"),(2, "pale beige")]),
                ("mirrored chartreuse", [(2, "mirrored tomato"),(4, "posh lime"),(5, "posh tan"),(4, "pale aqua")]),
                ("bright blue", [(3, "dark violet")]),
                ("mirrored yellow", [(2, "pale tomato"),(4, "vibrant gold"),(1, "faded teal"),(2, "bright purple")]),
                ("plaid black", [(2, "plaid purple"),(5, "dotted bronze")]),
                ("shiny silver", [(1, "dull lavender"),(5, "pale magenta"),(2, "drab white")]),
                ("mirrored salmon", [(1, "muted lime"),(4, "shiny bronze")]),
                ("muted maroon", [(3, "muted lime"),(1, "muted turquoise")]),
                ("light black", [(3, "striped beige"),(2, "shiny olive"),(2, "drab olive")]),
                ("wavy blue", [(2, "dull violet"),(1, "pale magenta"),(3, "bright black")]),
                ("light silver", [(1, "shiny bronze"),(2, "faded lavender")]),
                ("shiny coral", [(2, "mirrored tomato"),(2, "faded fuchsia"),(2, "striped violet"),(4, "shiny orange")]),
                ("striped coral", [(1, "clear indigo"),(3, "muted bronze"),(4, "shiny turquoise")]),
                ("shiny bronze", [(4, "light gold")]),
                ("bright crimson", [(4, "mirrored blue"),(3, "dull aqua"),(5, "muted lavender"),(1, "dotted turquoise")]),
                ("striped turquoise", [(3, "striped indigo"),(3, "clear fuchsia"),(4, "bright black"),(1, "vibrant aqua")]),
                ("faded green", [(3, "posh olive"),(4, "bright violet"),(5, "dull yellow"),(3, "dull olive")]),
                ("dark coral", [(2, "wavy green"),(2, "shiny cyan"),(5, "light red"),(3, "bright red")]),
                ("clear teal", [(3, "plaid beige"),(5, "faded aqua"),(2, "dim yellow"),(5, "bright gray")]),
                ("plaid chartreuse", [(2, "dark magenta"),(5, "wavy olive"),(2, "plaid plum")]),
                ("shiny aqua", [(1, "wavy indigo"),(1, "dull bronze"),(4, "shiny bronze")]),
                ("wavy salmon", [(2, "pale lime"),(4, "drab silver")]),
                ("striped yellow", [(4, "faded black")]),
                ("mirrored black", [(5, "muted yellow")]),
                ("bright gold", [(2, "mirrored crimson"),(1, "vibrant purple")]),
                ("vibrant purple", [(1, "muted tomato"),(5, "shiny green"),(1, "dark turquoise")]),
                ("dull fuchsia", [(1, "wavy gold"),(2, "plaid yellow")]),
                ("light maroon", [(5, "striped indigo"),(3, "muted red"),(3, "muted lime"),(2, "striped lavender")]),
                ("clear yellow", [(3, "plaid beige")]),
                ("clear tan", [(2, "vibrant red"),(4, "light chartreuse")]),
                ("dotted tomato", [(5, "vibrant black"),(5, "dotted gray"),(5, "plaid red")]),
                ("dark plum", [(5, "dotted orange"),(2, "mirrored blue"),(1, "light indigo")]),
                ("posh magenta", [(3, "dim gold"),(1, "drab coral"),(3, "shiny tomato")]),
                ("posh salmon", [(4, "posh tomato"),(3, "pale silver")]),
                ("vibrant bronze", [(4, "posh orange")]),
                ("dim tomato", [(2, "dull black"),(1, "striped aqua")]),
                ("posh white", [(3, "shiny plum"),(2, "wavy olive")]),
                ("mirrored plum", [(5, "dotted teal"),(2, "bright maroon")]),
                ("light coral", [(3, "dull brown"),(4, "pale red"),(4, "dull orange"),(5, "dim crimson")]),
                ("striped teal", [(1, "plaid plum"),(4, "striped tomato"),(1, "mirrored orange"),(5, "mirrored fuchsia")]),
                ("striped orange", [(4, "dark crimson"),(5, "drab green"),(5, "striped tan")]),
                ("dark gold", [(2, "bright plum"),(1, "striped purple"),(3, "wavy beige")]),
                ("drab fuchsia", [(5, "wavy orange")]),
                ("dull salmon", [(2, "dull olive"),(4, "bright silver"),(1, "muted tomato")]),
                ("shiny fuchsia", [(2, "mirrored fuchsia"),(1, "bright black"),(2, "clear orange"),(4, "wavy gold")]),
                ("clear bronze", [(4, "posh purple"),(3, "dim gold"),(3, "light chartreuse"),(1, "shiny cyan")]),
                ("dim gray", [(5, "muted beige"),(1, "dim purple")]),
                ("faded magenta", [(3, "mirrored aqua"),(3, "vibrant maroon"),(5, "drab red"),(1, "light magenta")]),
                ("muted fuchsia", [(1, "dim indigo"),(5, "vibrant purple"),(2, "posh silver")]),
                ("posh beige", [(3, "dark gold")]),
                ("bright yellow", [(2, "mirrored blue")]),
                ("clear orange", [(4, "vibrant purple"),(2, "clear fuchsia")]),
                ("pale salmon", [(4, "wavy black"),(3, "muted olive"),(5, "wavy teal"),(3, "dotted orange")]),
                ("dim chartreuse", [(1, "mirrored bronze"),(5, "shiny lavender"),(4, "dark red")]),
                ("clear gray", [(4, "bright indigo"),(5, "wavy coral"),(4, "drab tomato"),(1, "mirrored tomato")]),
                ("drab maroon", [(2, "dotted lime"),(2, "muted beige"),(2, "clear aqua"),(4, "drab silver")]),
                ("muted black", [(4, "wavy fuchsia"),(1, "striped cyan"),(4, "faded purple")]),
                ("clear blue", [(2, "striped teal")]),
                ("mirrored red", [(3, "posh plum"),(2, "striped beige")]),
                ("dull lavender", [(2, "vibrant purple")]),
                ("shiny maroon", [(4, "vibrant chartreuse")]),
                ("dim fuchsia", [(1, "striped maroon"),(3, "faded gray"),(4, "vibrant aqua")]),
                ("faded plum", [(5, "posh black"),(4, "striped turquoise"),(1, "striped plum")]),
                ("plaid cyan", [(1, "dim turquoise"),(1, "mirrored tan"),(5, "plaid fuchsia")]),
                ("muted olive", [(5, "wavy beige"),(5, "striped tomato"),(5, "posh tan"),(2, "pale magenta")]),
                ("dark cyan", [(5, "wavy green"),(4, "muted violet")]),
                ("vibrant lavender", [(1, "mirrored orange"),(4, "dull yellow"),(5, "bright silver")]),
                ("drab beige", [(1, "drab yellow")]),
                ("plaid indigo", [(5, "clear olive"),(4, "striped teal"),(4, "pale violet"),(4, "shiny gold")]),
                ("dark fuchsia", [(3, "drab magenta"),(1, "mirrored orange")]),
                ("faded chartreuse", [(5, "pale blue"),(3, "dim tan"),(5, "dull red"),(4, "wavy maroon")]),
                ("shiny orange", [(3, "dark gold"),(2, "posh silver"),(1, "dull cyan"),(4, "drab silver")]),
                ("striped black", [(5, "wavy teal"),(5, "light chartreuse"),(4, "wavy coral")]),
                ("light crimson", [(2, "dim gold")]),
                ("wavy yellow", [(2, "dark lime"),(1, "bright fuchsia"),(2, "plaid purple"),(4, "dark bronze")]),
                ("faded teal", [(3, "posh bronze"),(1, "striped yellow"),(3, "dim aqua")]),
                ("plaid gold", [(5, "bright black"),(2, "shiny yellow"),(5, "mirrored orange"),(5, "dark lime")]),
                ("clear beige", [(3, "faded blue"),(1, "plaid plum")]),
                ("dull plum", [(1, "mirrored green"),(3, "mirrored lime")]),
                ("bright beige", [(4, "shiny white"),(5, "faded teal"),(3, "mirrored plum")]),
                ("plaid turquoise", [(4, "striped gray")]),
                ("dark beige", [(5, "plaid brown"),(4, "bright plum")]),
                ("dull white", [(3, "posh coral")]),
                ("vibrant red", [(4, "plaid red")]),
                ("drab indigo", [(5, "shiny black"),(3, "mirrored brown"),(4, "muted olive"),(2, "mirrored coral")]),
                ("plaid lime", [(4, "dim gold")]),
                ("plaid tan", [(2, "dark fuchsia"),(3, "dotted purple"),(5, "dull bronze"),(3, "light blue")]),
                ("mirrored maroon", [(4, "mirrored green"),(1, "dark tomato")]),
                ("shiny red", [(1, "dim salmon"),(1, "plaid plum"),(4, "drab orange"),(5, "shiny teal")]),
                ("dark lime", [(4, "shiny white"),(3, "shiny indigo"),(4, "light cyan"),(2, "muted brown")]),
                ("dull yellow", [(3, "muted brown"),(1, "light maroon")]),
                ("mirrored silver", [(3, "pale brown"),(5, "mirrored yellow"),(1, "pale teal"),(4, "plaid red")]),
                ("light teal", [(3, "posh plum")]),
                ("drab tomato", [(2, "pale coral"),(5, "clear olive")]),
                ("mirrored lavender", [(3, "plaid fuchsia"),(3, "muted yellow")]),
                ("drab plum", [(5, "plaid olive")]),
                ("dotted purple", [(2, "plaid red"),(4, "mirrored bronze"),(5, "shiny teal"),(3, "dim blue")]),
                ("vibrant coral", [(1, "dotted lime"),(5, "shiny salmon"),(3, "mirrored blue"),(2, "striped indigo")]),
                ("faded olive", [(1, "drab blue"),(4, "vibrant indigo"),(3, "dotted lavender"),(5, "muted silver")]),
                ("wavy white", [(3, "mirrored maroon"),(2, "dim white"),(2, "dark magenta"),(4, "clear fuchsia")]),
                ("clear white", [(2, "light chartreuse"),(5, "plaid fuchsia"),(2, "drab lime"),(1, "clear indigo")]),
                ("pale blue", [(2, "dim crimson"),(4, "light green"),(4, "vibrant aqua"),(5, "drab white")]),
                ("mirrored olive", [(2, "bright gold"),(4, "bright tomato")]),
                ("vibrant salmon", [(5, "dim maroon"),(2, "dull cyan")]),
                ("plaid coral", [(1, "bright gray")]),
                ("plaid crimson", [(2, "muted black"),(3, "drab turquoise"),(2, "mirrored beige")]),
                ("faded maroon", [(5, "drab tan"),(4, "mirrored brown"),(1, "light silver")]),
                ("vibrant brown", [(2, "faded salmon"),(2, "posh plum"),(5, "wavy lime"),(2, "shiny beige")]),
                ("dull gold", [(5, "shiny salmon"),(3, "drab silver"),(1, "wavy beige")]),
                ("bright turquoise", [(5, "wavy blue"),(4, "muted chartreuse")]),
                ("light lavender", [(1, "drab olive"),(1, "posh violet")]),
                ("posh maroon", [(5, "bright chartreuse"),(4, "muted black"),(3, "dull tan"),(2, "mirrored gray")]),
                ("muted red", [(1, "striped crimson"),(5, "light blue")]),
                ("dark violet", [(2, "muted blue"),(1, "light bronze")]),
                ("striped chartreuse", [(1, "dark violet"),(1, "faded turquoise"),(3, "vibrant tomato"),(5, "dotted teal")]),
                ("dull turquoise", [(3, "drab tan")]),
                ("vibrant olive", [(2, "drab purple")]),
                ("shiny yellow", [(2, "faded lavender"),(4, "shiny cyan")]),
                ("posh lime", [(3, "light plum"),(4, "clear magenta")]),
                ("dotted aqua", [(3, "dim lime"),(2, "light green")]),
                ("dim yellow", [(4, "bright brown"),(4, "wavy coral")]),
                ("shiny blue", [(4, "dotted yellow"),(1, "dim crimson"),(1, "clear black")]),
                ("wavy maroon", [(4, "vibrant aqua"),(4, "striped bronze"),(3, "dotted silver")]),
                ("drab coral", [(1, "wavy teal"),(3, "plaid orange"),(2, "posh orange"),(1, "mirrored olive")]),
                ("bright teal", [(2, "pale magenta")]),
                ("bright purple", [(4, "shiny chartreuse"),(5, "plaid lime"),(2, "dim magenta")])] :: [(String, [(Int, String)])]